name: YouTube Discord Notify

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python src/script.py

      - name: Check last-notified.json
        shell: pwsh
        # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD

          # Check if a last-notified.json has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object last-notified.json
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "last_notified_changed"
          Write-Host "last_notified_changed=$HasDiff" >> $GITHUB_OUTPUT

      - name: Push last_notified.json
        if: steps.check_file_changed.outputs.last_notified_changed == 'True'
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add last_notified.json
          git commit -am "Update last_notified.json"
          git push
